name: Sync code without CSV

on:
  workflow_dispatch:
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  copy_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1
        uses: actions/checkout@v3
        with:
          repository: 'urquha/unit_testing_examples'
          path: 'unit_testing_examples'

      - name: Checkout repo2
        uses: actions/checkout@v3
        with:
          repository: 'urquha/test_actions'
          path: 'test_actions'
          
      - name: Copy code without CSV files
        run: |
          rsync -a --exclude='*.csv' unit_testing_examples/ test_actions/

      - name: Push changes
        run: |
          
          cd test_actions
        
          


          echo 1
          git config --local user.email "action@github.com"
          echo 2
          git config --local user.name "GitHub Action"
          git remote -v
          git remote set-url origin https://github.com/urquha/test_actions.git
          echo 6
          git config --get remote.origin.url
          git remote -v
          # git checkout -b main2
          # git push --set-upstream origin main2
          echo gitpull
          git config pull.ff only 
          git pull
          git status
          
          echo 3
          git add .
          echo 4
          git status
          git commit -m "Sync code from unit_testing_examples excluding CSV files"
          echo 5
          # response=$(curl -H "Authorization: token ${{ secrets.GH_PAT_TEST }}" https://api.github.com/urquha)
          # echo $response
          echo ${{ secrets.GH_PAT_TEST }}
          
          git push
