name: test push

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: './unit_testing_examples'

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: 'urquha/test_actions'
          token: ${{ secrets.GH_PAT_TEST }} # ensure this token has the right permissions
          path: './test_actions'

      - name: Copy files to target repository
        run: |
          cp -R ./unit_testing_examples/* ./test_actions/

      - name: Commit and push
        run: |
          cd ./test_actions
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from source repository"
          git push origin HEAD

      - name: Cleanup
        run: |
          cd ./test_actions
          rm -rf test.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from source repository"
          git push origin HEAD

