name: Sync code without CSV

on:
  workflow_dispatch:

jobs:
  copy_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1
        uses: actions/checkout@v3
        with:
          repository: 'urquha/unit_testing_examples'
          path: 'unit_testing_examples'

      - name: Checkout repo2
        uses: actions/checkout@v3
        with:
          repository: 'urquha/test_actions'
          path: 'test_actions'
          
      - name: Copy code without CSV files
        run: |
          rsync -a --exclude='*.csv' unit_testing_examples/ test_actions/

      - name: Push changes
        run: |
          cd test_actions
          echo 1
          git config --local user.email "action@github.com"
          echo 2
          git config --local user.name "GitHub Action"
          echo 3
          git add .
          echo 4
          git commit -m "Sync code from unit_testing_examples excluding CSV files"
          echo 5
          response=$(curl -H "Authorization: token ${{ secrets.GH_PAT_TEST }}" https://api.github.com/user)
          echo $response
          echo ${{ secrets.GH_PAT_TEST }}
          git remote set-url origin https://${{ secrets.GH_PAT_TEST }}@github.com/urquha/test_actions.git
          echo 6
          git push
