name: test push

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: urquha/test_actions
          path: test_actions

      - name: Commit and push
        run: |
          cd ./test_actions # Change directory to the 'test_actions'
          touch test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push origin HEAD

    
      
      # - uses: actions/checkout@v3
      # - run: |
      #     git pull
      #     ls
      #     echo ----
      #     rm -rf test.txt
      #     ls
      #     echo ----
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "generated"
      #     git push
